# fly.toml app configuration file generated for calendar-and-notebook on 2023-07-17T14:14:50+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calendar-and-notebook"
primary_region = "sin"

[env]
  PORT = "8081"
  HOST = "https://calendar-and-notebook.fly.dev"
  SHOPIFY_API_KEY = "59afa29795097893a49eec4991f1656a"
  SCOPES = "write_products"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
