# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec23bbd3ec5198aedf18fa5f40036f83"
name = "app-test-joy"
handle = "app-test-joy"
application_url = "https://element-heath-member-rep.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "joy-matubber-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://element-heath-member-rep.trycloudflare.com/auth/callback",
  "https://element-heath-member-rep.trycloudflare.com/auth/shopify/callback",
  "https://element-heath-member-rep.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "https://app-test--stageing-server.azurewebsites.net/webhooks"
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]

[pos]
embedded = false
